export const ADD_RECETAS = 'ADD_RECETAS';
export const RECETAS_FAILED = 'RECETAS_FAILED';
export const ADD_COMENTARIOS = 'ADD_COMENTARIOS';
export const NUEVO_COMENTARIO = 'NUEVO_COMENTARIO';
export const COMENTARIOS_FAILED = 'COMENTARIOS_FAILED';
export const ADD_USUARIO = 'ADD_USUARIO';
export const USUARIO_FAILED = 'USUARIO_FAILED';